# Generated by Django 6.0.2 on 2026-02-28 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_testimonial_delete_heroslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('aluminium_windows', 'Aluminium Windows'), ('glass_work', 'Glass Work'), ('acp_sheet', 'ACP Sheet'), ('hpl_sheet', 'HPL Sheet'), ('upvc', 'UPVC Windows & Doors'), ('interior_design', 'Interior Design'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Describe your requirement in detail')),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
